services:
  cypress:
    image: cypress/included:10.7.0
    depends_on:
      - client
      - web
    network_mode: host
    environment:
      CYPRESS_baseUrl: http://localhost:8082
      CYPRESS_reporter: junit
#      ELECTRON_ENABLE_LOGGING: 1
    working_dir: /e2e
    volumes:
      - ../:/e2e
  client:
    build: ..
    ports:
      - 8082:80
    environment:
      JASPER_API: //localhost:8081
      CSP_DEFAULT_SRC: http://localhost:8081
      JASPER_TITLE: CYPRESS
    depends_on:
      - web
  web:
    image: ghcr.io/cjmalloy/jasper
    ports:
      - 8081:8081
    environment:
      SPRING_PROFILES_ACTIVE: dev,jwt,feed-burst,repl-burst,storage
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jasper
      SPRING_DATASOURCE_USERNAME: jasper
      SPRING_DATASOURCE_PASSWORD: jasper
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: jasper
      POSTGRES_PASSWORD: jasper
      POSTGRES_DB: jasper
