services:
  cypress:
    image: cypress/included:10.9.0
    profiles:
      - ci
    depends_on:
      - client
      - repl-client
    network_mode: host
    environment:
      CYPRESS_baseUrl: http://localhost:8080
      CYPRESS_mainApi: http://web
      CYPRESS_replUrl: http://localhost:8082
      CYPRESS_replApi: http://repl-web
      CYPRESS_reporter: cypress-mochawesome-reporter
#      ELECTRON_ENABLE_LOGGING: 1
    working_dir: /e2e
    volumes:
      - ../:/e2e
  client:
    build: ..
    ports:
      - 8080:80
    environment:
      JASPER_API: //localhost:8081
      CSP_DEFAULT_SRC: http://localhost:8081
      JASPER_TITLE: CYPRESS
    depends_on:
      - web
  web:
    image: ghcr.io/cjmalloy/jasper
    ports:
      - 8081:80
    environment:
      SPRING_PROFILES_ACTIVE: prod,jwt,feed-burst,repl-burst,storage
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/jasper
      SPRING_DATASOURCE_USERNAME: jasper
      SPRING_DATASOURCE_PASSWORD: jasper
      SERVER_PORT: 80
      JASPER_SECURITY_AUTHENTICATION_JWT_CLIENT_ID: ''
      JASPER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET: 'MjY0ZWY2ZTZhYmJhMTkyMmE5MTAxMTg3Zjc2ZDlmZWUwYjk0MDgzODA0MDJiOTgyNTk4MmNjYmQ4Yjg3MmVhYjk0MmE0OGFmNzE2YTQ5ZjliMTEyN2NlMWQ4MjA5OTczYjU2NzAxYTc4YThkMzYxNzdmOTk5MTIxODZhMTkwMDM='
      JASPER_HEAP: 64m
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: jasper
      POSTGRES_PASSWORD: jasper
      POSTGRES_DB: jasper
  repl-client:
    build: ..
    ports:
      - 8082:80
    environment:
      JASPER_API: //localhost:8083
      CSP_DEFAULT_SRC: http://localhost:8083
      JASPER_TITLE: REPL
    depends_on:
      - repl-web
  repl-web:
    image: ghcr.io/cjmalloy/jasper
    ports:
      - 8083:80
    environment:
      SPRING_PROFILES_ACTIVE: prod,jwt,feed-burst,repl-burst,storage
      SPRING_DATASOURCE_URL: jdbc:postgresql://repl-db/jasper
      SPRING_DATASOURCE_USERNAME: jasper
      SPRING_DATASOURCE_PASSWORD: jasper
      SERVER_PORT: 80
      JASPER_SECURITY_AUTHENTICATION_JWT_CLIENT_ID: ''
      JASPER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET: 'MjY0ZWY2ZTZhYmJhMTkyMmE5MTAxMTg3Zjc2ZDlmZWUwYjk0MDgzODA0MDJiOTgyNTk4MmNjYmQ4Yjg3MmVhYjk0MmE0OGFmNzE2YTQ5ZjliMTEyN2NlMWQ4MjA5OTczYjU2NzAxYTc4YThkMzYxNzdmOTk5MTIxODZhMTkwMDM='
      JASPER_HEAP: 64m
    depends_on:
      - repl-db
  repl-db:
    image: postgres
    environment:
      POSTGRES_USER: jasper
      POSTGRES_PASSWORD: jasper
      POSTGRES_DB: jasper
