services:
  cypress:
    image: cypress/included:10.7.0
    profiles:
      - ci
    depends_on:
      - client
      - web
    network_mode: host
    environment:
      CYPRESS_baseUrl: http://localhost:8082
      CYPRESS_replUrl: http://localhost:8084
      CYPRESS_replApi: http://localhost:8083
      CYPRESS_reporter: junit
#      ELECTRON_ENABLE_LOGGING: 1
    working_dir: /e2e
    volumes:
      - ../:/e2e
  client:
    build: ..
    ports:
      - 8082:80
    environment:
      JASPER_API: //localhost:8081
      CSP_DEFAULT_SRC: http://localhost:8081
      JASPER_TITLE: CYPRESS
    depends_on:
      - web
  web:
    image: ghcr.io/cjmalloy/jasper
    network_mode: host
    environment:
      SPRING_PROFILES_ACTIVE: dev,jwt,feed-burst,repl-burst,storage
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/jasper
      SPRING_DATASOURCE_USERNAME: jasper
      SPRING_DATASOURCE_PASSWORD: jasper
      SERVER_PORT: 8081
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: jasper
      POSTGRES_PASSWORD: jasper
      POSTGRES_DB: jasper
  repl-client:
    build: ..
    ports:
      - 8084:80
    environment:
      JASPER_API: //localhost:8083
      CSP_DEFAULT_SRC: http://localhost:8083
      JASPER_TITLE: REPL
    depends_on:
      - repl-web
  repl-web:
    image: ghcr.io/cjmalloy/jasper
    network_mode: host
    environment:
      SPRING_PROFILES_ACTIVE: dev,jwt,feed-burst,repl-burst,storage
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5434/jasper
      SPRING_DATASOURCE_USERNAME: jasper
      SPRING_DATASOURCE_PASSWORD: jasper
      SERVER_PORT: 8083
    depends_on:
      - repl-db
  repl-db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: jasper
      POSTGRES_PASSWORD: jasper
      POSTGRES_DB: jasper
