name: Cypress

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Start containers
        run: npm run cy:ci

      - name: Publish Unit Test Results
        uses: dorny/test-reporter@v1.5.0
        if: always()
        with:
          name: Test Results
          path: "cypress/results-combined.xml"
          reporter: java-junit

      - name: Publish Screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Publish Videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
